sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: WbkBieywNcqlh0Vvo8R+ZeK/UjOhB5nBNE6byo1NvUc+7cm0SHMCFe+/2FWh3iYebO6ji/RL42IS6lNvuFYtg45W3Ndl0qARj68wVUPgcTaDptK4C6OLvT1CPIlKi37CmSFYPd+nh3LoibVg7v/zJgVkQ8ggA4UGbK3GofS9zVUV7/znkFhpvklyYgb6EORvc4BZ1dxUgdLqG2jWMg8DsaOXdsuUQ/1UG9N2IF6E7+LCaaLSKhoLYnh+CVjhvThRa8S01YRwCRnlwxV0/Dn1/ZBSzlJebkRQCXVfpF0oabAKIfhMwFOVe/O4/FDXsO/0tftwV3jkIYTSgYBPKVst+hKSOreXOeemykGzgKYDazV2EYioSi5HXfj8odXQVoHK7OSU9G/yDD4bJDxt//s+RIygqcIU102grroC2XnM7trWcVMRfv6aPXju8EGUQh8HCKeJeSoGLibEvgcMxJvcyMyhzNcEznxXnZPP5VBpp1/aQhb+J+t6NBKULk2bp8uMQR9jz6xP/vKwwb9Ujitu32bV454Wo5w9E7dJ1QwGY552ujKlkZNFvrIZkB+5t3UO8r2IdvkrtsoyqJ9BH3gSColG15ZwQIGxm5JQJ4OaJZy5gJqhjN+NAF2I7WqQ3GPVWlbGFzEtmWk3vG1sh/pDgpXjwtCli0KRJKgZbm7ZcCA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Silver-Box--A-Comedy-in-Three-Acts_2906
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy